name = "PlutoMathInput"
uuid = "4bac68be-45d4-40a9-9f37-f14fc6d2878f"
authors = ["SÃ©bastien Celles"]
version = "0.3.0"

[deps]
AbstractPlutoDingetjes = "6e696c72-6542-2067-7265-42206c756150"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
AbstractPlutoDingetjes = "1"
HypertextLiteral = "0.9"
JSON3 = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
